"""empty message

Revision ID: 6096d09575fd
Revises: 9becf373e218
Create Date: 2026-06-03 15:32:03.443032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6096d09575fd'
down_revision: Union[str, Sequence[str], None] = '9becf373e218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_project_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('external_place_id', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('visited', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['travel_projects.id'], name=op.f('travel_project_places_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('travel_project_places_pkey'))
    )
    op.create_index(op.f('travel_project_places_project_id_idx'), 'travel_project_places', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('travel_project_places_project_id_idx'), table_name='travel_project_places')
    op.drop_table('travel_project_places')
    # ### end Alembic commands ###
