"""empty message

Revision ID: 5a3a78f7a21a
Revises: 6096d09575fd
Create Date: 2026-06-03 17:04:15.053207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3a78f7a21a'
down_revision: Union[str, Sequence[str], None] = '6096d09575fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_place', 'travel_project_places', ['project_id', 'external_place_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_place', 'travel_project_places', type_='unique')
    # ### end Alembic commands ###
